baseURL = "https://tutorials.groupdocs.cloud/annotation"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-T42TVBC"

[[deployment.targets]]
name = "Production"
URL = "s3://tutorials.groupdocs.cloud/?prefix=annotation/&region=us-west-2"
