baseURL = "https://tutorials.aspose.cloud/slides"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-TSXP9CZ"

[[deployment.targets]]
name = "Production"
URL = "s3://tutorials.aspose.cloud/?prefix=slides/&region=us-west-2"
