baseURL = "https://tutorialsgroupdocs.cloud/viewer"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-T42TVBC"

[[deployment.targets]]
name = "Production"
URL = "s3://tutorialsgroupdocs.cloud/?prefix=viewer/&region=us-west-2"
